dist: trusty
sudo: required
language: php
php:
  #- "7.1"
  - hhvm-3.12
before_script: |
  if [[ ! $TRAVIS_PHP_VERSION =~ 'hhvm' ]] ; then
  phpenv config-add php.ini
  pecl config-set preferred_state beta
  echo yes | pecl install apcu
  fi
  composer self-update
  composer install --prefer-source --no-interaction --dev
script:
  - vendor/bin/paratest
